name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Clean up disk space first
            docker system prune --all --force --volumes
            rm -rf /tmp/*
            sudo apt-get clean

            cd /home/***/myproject
            git fetch origin main
            git reset --hard origin/main

            # Check which docker-compose command works
            if command -v docker-compose &> /dev/null; then
              docker-compose up -d --build
            else
              docker compose up -d --build
            fi
